spring.application.name=MedAccess
spring.datasource.url=jdbc:mysql://localhost:3306/medaccess
spring.datasource.username=root
spring.datasource.password=Akhil@987

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secretKey=QWERTY234567xcvbnmtrfghjtdfghjopresxcvbnmertyuicvhjhgiuyiy

spring.security.oauth2.client.registration.google.client-id=ksddjfuief
spring.security.oauth2.client.registration.google.client-secret=jasjjefjewo